//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ecommerce.DataLayer.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class DonHang
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DonHang()
        {
            this.DonHangCTs = new HashSet<DonHangCT>();
        }
    
        public int ID { get; set; }
        public string MaDonHang { get; set; }
        public System.DateTime NgayLap { get; set; }
        public int KhachHangID { get; set; }
        public string NguoiNhan { get; set; }
        public string DiaChiNhan { get; set; }
        public string SdtNguoiNhan { get; set; }
        public int HinhThucThanhToan { get; set; }
        public decimal PhiVanChuyen { get; set; }
        public int TinhTrangDonHang { get; set; }
        public string GhiChu { get; set; }
    
        public virtual KhachHang KhachHang { get; set; }
        public virtual HinhThucThanhToan HinhThucThanhToan1 { get; set; }
        public virtual TinhTrangDonHang TinhTrangDonHang1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DonHangCT> DonHangCTs { get; set; }
    }
}
