//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ecommerce.DataLayer.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class ThuocTinh
    {
        public int ID { get; set; }
        public int NhomSanPhamID { get; set; }
        public string MaThuocTinh { get; set; }
        public string TenThuocTinh { get; set; }
        public string DonViTinh { get; set; }
    
        public virtual NhomSanPham NhomSanPham { get; set; }
    }
}
